apiVersion: v1
kind: Pod
metadata:
  name: nfstream-pod
  namespace: nfstream
spec:
  containers:
  - name: nfstream
    image: alextlittle/nfstream-ml-app:v2
    imagePullPolicy: Never
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    securityContext:
      privileged: true